name: iOS starter workflow

on:
  push:
    branches: 
    - main
    - develop
  pull_request:
    branches:
    - main
    - develop

jobs:
  build:
    name: Lint, build and test using any available iPhone simulator
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: SwiftLint
      run: swiftlint lint

    - name: Test on iOS 16.2
      run: xcodebuild -workspace Cookbook.xcworkspace -scheme Cookbook -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=16.2,name=iPhone 14' test

    - name: Build on iOS 16.2
      run: xcodebuild -workspace Cookbook.xcworkspace -scheme Cookbook -sdk iphonesimulator -destination 'platform=iOS Simulator,OS=16.2,name=iPhone 14'
